require 'rspec_extensions_collection/helpers/mongoid_model_helpers'
require 'rspec_extensions_collection/matchers/search_matcher'
require 'rspec_extensions_collection/matchers/search_embedded_matcher'